### ISSUE TITLE
The scratch (to start from)

### ISSUE THREAD

**Issue by barroisr** [BITPlan/com.bitplan.simplegraph#1]
The idea is to build up a system of modules implementing an interface to often used standard systems or datasources. The wanted interface offers a simple graph representation of the datastructure of the system or datasource where it is implemented for. The requirement is to set up a graph with typecasting nodes and links. The nodes represent interfaces to navigate the graph on the one hand. On the other hand there are domain specific interfaces leading to the domain specific informations as well as technical specific interfaces for example a printertype specific access.

At the beginning the following modules are required:

Module to

- access a file system

- access a database (encapsulate sql)

- access to mediawikis

**Comment by WolfgangFahl** [comment]
The first three module have initial implementations and test cases see #2 #3 #4

**Comment by WolfgangFahl** [comment]
#5 adds a GitHub Module
#6 adds a HTML Module
#7 adds a PowerPoint Module

**Comment by WolfgangFahl** [comment]
#13 adds a CardDAV Module
#14 adds a CalDAV Module
#19 adds a Geo-Module
