### ISSUE TITLE
Traditional pdf indexing solution compared to graph-based version

### ISSUE THREAD

**Issue by pdvsofismo** [BITPlan/com.bitplan.simplegraph#16]
I asked the question on Stackoverflow and was requested to file an issue here:

https://stackoverflow.com/q/51800068/10211666

**Comment by WolfgangFahl** [comment]
The core of your question was already discussed in https://stackoverflow.com/questions/50314987/gremlin-text-comparison-predicates with https://github.com/BITPlan/com.bitplan.simplegraph/blob/master/simplegraph-core/src/main/java/com/bitplan/gremlin/RegexPredicate.java being the main part of the solution.

For the rest mostly gremlin and SimpleGraph solutions are already in place. You'll find the code now refactored in:
https://github.com/BITPlan/com.bitplan.simplegraph/blob/master/simplegraph-bundle/src/test/java/com/bitplan/simplegraph/bundle/TestTraditionalPDFIndexing.java

and 

https://github.com/BITPlan/com.bitplan.simplegraph/blob/master/simplegraph-bundle/src/test/java/com/bitplan/simplegraph/bundle/TestPDFFiles.java

See also my answer https://stackoverflow.com/a/51800265/1497139
