### ISSUE TITLE
PowerPoint-Module

### ISSUE THREAD

**Issue by daniel-fleck** [BITPlan/com.bitplan.simplegraph#7]
The PowerPoint Module shall make PowerPoint content accessible to Graph processing with Gremlin
Presentations with their slides and slidecontent like notes, tables according to the Apache POI
interfaces should be made available.

It should be possible to create presentations from Graph data (presentation slides, tables, notes, headlines, ...)

**Comment by WolfgangFahl** [comment]
Documentation and test case is available at http://wiki.bitplan.com/index.php/SimpleGraph-PowerPoint
