### ISSUE TITLE
SimpleGraph Excel module isn't able to create CSV file (automatically)

### ISSUE THREAD

**Issue by wzimni** [BITPlan/com.bitplan.simplegraph#9]
I tried to create a CSV file, but result was also a xlsx file instead, although it was named *.csv. It is possible to create such a file from its filename in a correct format or should there exist a method or parameters to create a csv file explicite (also a parameter for the delimter). Perhaps also other export formats from Excel.

A CSV file make only sense for a single sheet. So a CSV converter should create separate files with <filename>-<sheet[name] | sheet[number]>.csv

<pre><code>
public void testCreateExcelCSVTracks() throws Exception {
    ExcelSystem es = new ExcelSystem();
    Graph graph = TinkerGraph.open();
    graph.io(IoCore.graphml()).readGraph("tracks.graphml");
    if (debug)
      LOGGER.log(Level.INFO, graph.toString());

    GraphTraversalSource g = graph.traversal();
    // es.setDebug(true);
    Workbook wb = es.createWorkBook(g);
    assertEquals(3, wb.getNumberOfSheets());
    es.save(wb, "tracks.csv");
  }
</code></pre>

**Comment by WolfgangFahl** [comment]
Could you please upload the tracks.graphml somewhere...

**Comment by wzimni** [comment]
Gesendet: Freitag, 16. März 2018 um 20:27 Uhr
Von: "Wolfgang Fahl" <notifications@github.com>
An: "BITPlan/com.bitplan.simplegraph" <com.bitplan.simplegraph@noreply.github.com>
Cc: wzimni <werner.zimni@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [BITPlan/com.bitplan.simplegraph] SimpleGraph Excel module isn't able to create CSV file (automatically) (#9)


Could you please upload the tracks.graphml somewhere...

**Comment by wzimni** [comment]
Hi Wolfgang,

I have tried to convert an Excel Workbook by myself. It seems to work - with a little help by another stackoverflow.

Parameters are:
XSSFSheet sheet - a single sheet of the workbook
String delimiter - to separate the cell values
returns a string with all rows and cells from the sheet

Should I send you the code per mail or drop it here in another comment?

**Comment by WolfgangFahl** [comment]
CSV via Excel is probably much slower than going directly with a CSV library. See e.g. https://commons.apache.org/proper/commons-csv/

**Comment by WolfgangFahl** [comment]
https://stackoverflow.com/a/23454657/1497139 points to some add on libraries

**Comment by WolfgangFahl** [comment]
Since Apache POI doesn't support this out of the box SimpleGraph won't either (for the time being). We may well reopen this issue if the priority of this need increases (e.g. more users asking for it).
